### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ProGamer13** [TypeCtrl/cloudflare#11]
const options: any = {
        ^^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11

**Comment by scttcper** [comment]
are you using typescript?

**Comment by ProGamer13** [comment]
What do you mean i am using on linux server trying to run

**Comment by scttcper** [comment]
get rid of the `:any` if you are not using typescript
