### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ProGamer13** [TypeCtrl/cloudflare#17]
/root/got.js:10
  const options: GotOptions<any> = {
        ^^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

**Comment by scttcper** [comment]
you're copy pasting typescript code and trying to use javascript. you will need to remove the typescript types eg - `GotOptions`
